name: Release

on:
  workflow_dispatch:  # 允许手动触发
    inputs:
      version:
        description: 'New version tag (e.g., v1.0.1)'
        required: true
        default: 'v1.0.0'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Generate source package
        id: source-package
        run: |
          VERSION=$(echo "${{ github.event.inputs.version }}" | sed 's/^v//')
          mkdir -p pver-$VERSION

          # 正确复制项目文件，避免循环复制
          find . -mindepth 1 -maxdepth 1 \
            \( -name "pver-$VERSION" -o -name ".git" -o -name ".github" \) -prune -o \
            -exec cp -r '{}' pver-$VERSION/ \;

          tar czvf pver-$VERSION.tar.gz pver-$VERSION
          SHA256=$(sha256sum pver-$VERSION.tar.gz | awk '{print $1}')

          PKGBUILD_PATH=$(find . -name "PKGBUILD" | head -n 1)
          if [ -z "$PKGBUILD_PATH" ]; then
            echo "pkgbuild_found=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "pkgbuild_found=true" >> $GITHUB_OUTPUT
            sed -i "s/pkgver=.*/pkgver=$VERSION/" "$PKGBUILD_PATH"
            sed -i "s/sha256sums=('.*')/sha256sums=('$SHA256')/" "$PKGBUILD_PATH"
            echo "pkgbuild_path=$PKGBUILD_PATH" >> $GITHUB_OUTPUT
          fi

          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Commit updated PKGBUILD
        if: steps.source-package.outputs.pkgbuild_found == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ${{ steps.source-package.outputs.pkgbuild_path }}
          git commit -m "Update PKGBUILD for ${{ github.event.inputs.version }}" || echo "No changes"
          git push || echo "Nothing to push"

      - name: Create Git Tag
        run: |
          git tag -a ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.version }}

  build-and-release:
    needs: prepare-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          output_name=pver
          [ "${{ matrix.goos }}" = "windows" ] && output_name=pver.exe
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $output_name main.go

      - name: Archive binary
        id: archive
        run: |
          archive_name="pver_${{ matrix.goos }}_${{ matrix.goarch }}_${{ github.event.inputs.version }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip -r ${archive_name}.zip pver.exe
            echo "archive_file=${archive_name}.zip" >> $GITHUB_OUTPUT
          else
            tar czvf ${archive_name}.tar.gz pver
            echo "archive_file=${archive_name}.tar.gz" >> $GITHUB_OUTPUT
          fi

  arch-release:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Generate Arch source package
        id: arch-package
        run: |
          VERSION=$(echo "${{ github.event.inputs.version }}" | sed 's/^v//')
          mkdir -p pver-$VERSION
          find . -mindepth 1 -maxdepth 1 \
            \( -name "pver-$VERSION" -o -name ".git" -o -name ".github" \) -prune -o \
            -exec cp -r '{}' pver-$VERSION/ \;

          tar czvf pver-arch-$VERSION.tar.gz pver-$VERSION
          echo "archive_file=pver-arch-$VERSION.tar.gz" >> $GITHUB_OUTPUT

      - name: Upload Arch source tarball
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.arch-package.outputs.archive_file }}
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-release:
    needs: [build-and-release, arch-release]
    runs-on: ubuntu-latest
    steps:
      - name: Upload all release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pver_*_*_${{ github.event.inputs.version }}.*
            pver-arch-*.tar.gz
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
