name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.0.2)'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setvars.outputs.version }}
      short_version: ${{ steps.setvars.outputs.short_version }}
      sha256: ${{ steps.sha.outputs.sha256 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version variables
        id: setvars
        run: |
          VERSION="${{ github.event.inputs.version }}"
          SHORT_VER="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "short_version=${SHORT_VER}" >> $GITHUB_OUTPUT

      - name: Package source and compute SHA256
        id: sha
        run: |
          SHORT_VER="${{ steps.setvars.outputs.short_version }}"

          mkdir -p pver-${SHORT_VER}
          rsync -a --exclude "pver-${SHORT_VER}" ./ pver-${SHORT_VER}/
          tar czf pver-${SHORT_VER}.tar.gz pver-${SHORT_VER}

          SHA=$(sha256sum pver-${SHORT_VER}.tar.gz | awk '{print $1}')
          echo "sha256=$SHA" >> $GITHUB_OUTPUT

          echo "✅ Source tarball created: pver-${SHORT_VER}.tar.gz"
          echo "✅ SHA256: $SHA"

      - name: Update PKGBUILD
        run: |
          SHORT_VER="${{ steps.setvars.outputs.short_version }}"
          SHA256="${{ steps.sha.outputs.sha256 }}"
          sed -i "s/^pkgver=.*/pkgver=${SHORT_VER}/" pkgbuild/PKGBUILD
          sed -i "s/^sha256sums=(.*/sha256sums=('${SHA256}')/" pkgbuild/PKGBUILD

      - name: Commit updated PKGBUILD
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add pkgbuild/PKGBUILD
          git commit -m "Update PKGBUILD for release ${{ steps.setvars.outputs.version }}" || echo "No changes"
          git push

      - name: Tag version
        run: |
          git tag -a ${{ steps.setvars.outputs.version }} -m "Release ${{ steps.setvars.outputs.version }}"
          git push origin ${{ steps.setvars.outputs.version }}

  build-and-release:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout tagged release
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.prepare.outputs.version }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: |
          output_name=pver
          [ "${{ matrix.goos }}" = "windows" ] && output_name=pver.exe
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $output_name main.go

      - name: Archive binary
        id: archive
        run: |
          archive="pver_${{ matrix.goos }}_${{ matrix.goarch }}_${{ needs.prepare.outputs.version }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip -r ${archive}.zip pver.exe
            echo "archive_file=${archive}.zip" >> $GITHUB_OUTPUT
          else
            tar czf ${archive}.tar.gz pver
            echo "archive_file=${archive}.tar.gz" >> $GITHUB_OUTPUT
          fi

      - name: Upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.archive.outputs.archive_file }}
          tag_name: ${{ needs.prepare.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-source:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Upload source tarball
        uses: softprops/action-gh-release@v1
        with:
          files: pver-${{ needs.prepare.outputs.short_version }}.tar.gz
          tag_name: ${{ needs.prepare.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
